---
title: "instacart_plotly"
author: "Xiaoyu Wu"
date: "2023-10-24"
output: html_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
```

## Import and Filter `Instacart` Dataset 
```{r}
data(instacart)
   instacart_df = instacart |> 
     select(
    order_id, order_hour_of_day, product_name, aisle,department,add_to_cart_order) |>         sample_n(size = 10000)
```

## Make a ScatterPlot: Time in a Day vs. Frequency of Ordering of Different Departments  

```{r, warning=FALSE}
filtered_hour = instacart_df |>
  filter(add_to_cart_order == 1) |>
  group_by(department, order_hour_of_day) |>
  summarise(item_count = n()) |>
  arrange(item_count) |>
plot_ly(x = ~order_hour_of_day, type = "scatter", mode = "markers", color = ~department, alpha = 0.5) |>
  layout(xaxis = list(title = "Hours in a Day"),
         yaxis = list(title = "Frequency of Ordering"),
         colorbar = list(title = "Department Names"))
filtered_hour
```

## Make a BarPlot: Count on the Number of Orders of each Aisle in Bakery Department 
```{r}
instacart_df |> 
  filter(department=="bakery") |>
  count(aisle) |>
  mutate(aisle = fct_reorder(aisle, n)) |>
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis") |> 
    layout(xaxis = list(title = "Aisle"),
         yaxis = list(title = "Number of Orders"))
```
## Make a BoxPlot: When the Products of each Department were Ordered 
```{r}
instacart_df  |>  
  mutate(department = fct_reorder(department, order_hour_of_day)) |>  
  plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis") |> 
    layout(xaxis = list(tickangle = 35,title = "Department"),
         yaxis = list(title = "Hours in a Day"))
```
```
